added base code for ingestor and climber
FRC2832/Robot2022-2832 pull request #26
Opened 2022-03-03 00:18 UTC by hjicarus5602

this commit contains the initial classes for climber and ingestor (will be developed more in days to come)

2022-03-03 05:23 UTC, PNovak619 commented
Hi Harish - the climber code seems to be for shooter, or at least references shooter motor.  It should reference the rung 1 winch motor from the Electrical DT file in the Integration Drive.  Let me know if I misread something.

2022-03-04 23:28 UTC, programmer94 requested changes
Confirm or correct these variable names, and I'll approve your PR.

2022-03-04 23:28 UTC, programmer94 commented on src/main/java/frc/robot/Climber.java
> +    private WPI_TalonSRX liftGate;
Are you sure these variable names are correct?

2022-03-05 00:58 UTC, programmer94 approved these changes
Looks fine to me.

2022-03-05 00:58 UTC, merged